### ISSUE TITLE
no load_dataset in dataset module.

### ISSUE THREAD

**Issue by a-m-farahani** [tezansahu/VQA-With-Multimodal-Transformers#2]
Hi, 
I cant find load_dataset in dataset folder or any other places.

**Comment by tezansahu** [comment]
`load_dataset()` is a function available in the `datasets` library by Hugging Face, which you need to install before running the notebook.
The exact version (1.17.0) of the library is mentioned in the Prerequisites section in the README.

Hope this addresses your issue.
